spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        show_sql: true
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    password: sa
    url: jdbc:h2:mem:test_db