-- INSERT INTO employee(id, email, name, last_name, department) VALUES (1, 'ivan@email.com', 'Ivan', 'Reyes', 'FRONTEND')
-- INSERT INTO employee(id, email, name, last_name, department) VALUES (2, 'ivan@email.com', 'Melissa', 'Lara', 'DBA')
-- INSERT INTO employee(id, email, name, last_name, department) VALUES (3, 'ivan@email.com', 'Santiago', 'Jimenez', 'BACKEND')
-- INSERT INTO employee(id, email, name, last_name, department) VALUES (4, 'ivan@email.com', 'Ricardo', 'Urrutia', 'HR')
-- INSERT INTO employee(id, email, name, last_name, department) VALUES (5, 'ivan@email.com', 'Juan', 'Dominguez', 'DATA_ENGINEER')
--
--
-- INSERT INTO review(id, title, review_type, employee_id) VALUES (1, 'title', 'FIRST_QUARTER', 1);
-- INSERT INTO review(id, title, review_type, employee_id) VALUES (2, 'title', 'SECOND_QUARTER', 1);
-- INSERT INTO review(id, title, review_type, employee_id) VALUES (3, 'title', 'THIRD_QUARTER', 1);
-- INSERT INTO review(id, title, review_type, employee_id) VALUES (4, 'title', 'FOURTH_QUARTER', 1);
--
